### ISSUE TITLE
Internal error 500

### ISSUE THREAD

**Issue by ashrafalzyoud** [agileware-jp/redmine_issue_trash#19]
when i click in issue deleted
```
ActionView::Template::Error (undefined method `render_author_indicator' for #<ActionView::Base:0x00000000075940>):
    14:     <h4 class="note-header">
    15:       <%= avatar(journal.user) %>
    16:       <%= authoring journal.created_on, journal.user, :label => :label_updated_time_by %>
    17:       <%= ::Temple::Utils.escape_html_safe((render_author_indicator issue, journal if Additionals.setting? :issue_note_with_author)) %>
    18: <%= render_private_notes_indicator(journal) %>
    19:       <%= render_journal_update_info(journal) %>
    20:     </h4>
  
app/views/issues/tabs/_history.html.erb:17
app/views/issues/tabs/_history.html.erb:7
app/views/common/_tabs.html.erb:21
app/views/common/_tabs.html.erb:20:in `each'
app/views/common/_tabs.html.erb:20
app/helpers/application_helper.rb:499:in `render_tabs'
plugins/redmine_issue_trash/app/views/trashed_issues/show.html.erb:118
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by ashrafalzyoud** [comment]
@zh 
@agilekawabata 
@rewish 
@nishidayuya
